version: '3.9'

services:
  #mongoDB container
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    env_file:
      - .envs/.env.dev
    volumes: 
      mongo_db: /data/db

  #node api container
  api:
    build: .
    ports: 
      -5000:5000
    env_file:
      - .envs/.env.dev
    depends_on:
      - mongo_db

volumes:
  mongo_db:   
